GET http://localhost:3002/api/persons

###

GET http://localhost:3002/info

###

POST http://localhost:3002/api/persons

Content-Type: application/json
{
    "name" : "Hasna",
    "number" : "12345"
}
###

DELETE http://localhost:3002/api/persons/1